elementary/settings-daemon

- debian/control
Missing dependencies causes [build failing on Launchpad](https://launchpadlibrarian.net/499889882/buildlog_ubuntu-focal-amd64.io.elementary.settings-daemon_1.0.0+r9+pkg3~daily~ubuntu6.0.1_BUILDING.txt.gz)
> Add granite and geoclue as dependencies

- meson.build
- src/meson.build
GLib.Variant is used in the code and that comes from glib-2.0.
Not sure about making version constraints on gio and glib, though. It should be done in the future.
> build: add glib dependency

- src/Backends/PrefersColorSchemeSettings.vala
This does the least to mirror dark style to gsettings. If we ever change the code in Granite then we'll need to port that here
> Mirror Granite.Settings to gsettings

- .editorconfig
- data/io.elementary.settings-daemon.gschema.xml
- src/Backends/PrefersColorSchemeSettings.vala
Fixes #16. Follows the same terminology used elsewhere and documented at https://github.com/elementary/os/wiki/Dark-Style-Preference. 
While I was here I bumped copyright, fixed whitespace (Mixed tabs and spaces! Boo! Hiss!), added .editorconfig to prevent that from happening in the future, and renamed `update ()` to `update_timer ()` so it's more clear what it does.
> Add GSetting for dark style preference

- src/Backends/PrefersColorSchemeSettings.vala
Fixes elementary/switchboard-plug-pantheon-shell#273.
> Fix Range Check After Midnight When `from > to`

- data/io.elementary.settings-daemon.gschema.xml
- src/Application.vala
- src/Backends/Housekeeping.vala
- src/meson.build
Based on @cassidyjames 's tweet I saw: https://twitter.com/CassidyJames/status/1382045710883774466
It sounds like gsd-housekeeping may be killed in favour of systemd-tmpfiles at some point anyway, so we can probably get ahead of the curve here.
Adds two new GSettings keys to the settings-daemon namespace that allow enabling housekeeping of the user's downloads folder. The maximum age of files to be kept is configurable.
This uses systemd-tmpfiles to do the heavy lifting of running on a schedule and actually deleting the files.
I'll leave it up to someone else to develop the UI in switchboard and initial setup if we decide we want this.
> Use systemd-tmpfiles to allow Downloads folder housekeeping

- data/io.elementary.SettingsDaemon.AccountsService.xml
- src/AccountsService.vala
- src/Application.vala
- src/Backends/MouseSettings.vala
- src/meson.build
Related to https://github.com/elementary/initial-setup/pull/133
> Add left handed

- data/io.elementary.SettingsDaemon.AccountsService.xml
- po/ru.po
- src/AccountsService.vala
- src/Backends/MouseSettings.vala
Required for https://github.com/elementary/greeter/pull/655
> Expose user's mouse settings

- src/Backends/MouseSettings.vala
I want to return this back, because I suspect this is used by installer to set left handed mode. (This was removed in #66)
> Load left handed mode from settings-daemon

- data/io.elementary.SettingsDaemon.AccountsService.xml
- src/AccountsService.vala
- src/Application.vala
- src/Backends/KeyboardSettings.vala
- src/Backends/MouseSettings.vala
- src/Backends/NightLightSettings.vala
- src/meson.build
Required for https://github.com/elementary/greeter/pull/662
> Expose night light settings

- data/meson.build
- data/settings-daemon.metainfo.xml.in
- meson.build
- po/meson.build
- settings-portal/meson.build
> Fix autostart file symlink

- data/io.elementary.settings-daemon.check-for-firmware-updates.service.in
- data/meson.build
- meson_options.txt
(review with hide whitespace)
As a weird distro, we install packages in their own separate prefixes, which means we don't have `/usr/bin/busctl`, and we cannot install files to systemd's prefix.
(I can kill the `busctlpath` meson options if preferred, since we are not using `find_program` I assume cross compilation *should* be fine here?)
```
$ find | grep check-for-firmware-updates       
./lib/systemd/system/io.elementary.settings-daemon.check-for-firmware-updates.service
./lib/systemd/system/io.elementary.settings-daemon.check-for-firmware-updates.timer
$ cat ./lib/systemd/system/io.elementary.settings-daemon.check-for-firmware-updates.service | grep ExecStart
ExecStart=/nix/store/lhpz4ywr4dhbcxx688piqa7cv6vh15fd-systemd-253.5/bin/busctl --user call io.elementary.settings-daemon …
```
> Fix installing check-for-firmware-updates files in NixOS

- .github/workflows/main.yml
- README.md
- data/io.elementary.settings-daemon.gschema.xml
- meson.build
- src/Application.vala
- src/Backends/SystemUpdate.vala
- src/Backends/SystemUpdate/SystemUpdate.vala
- src/meson.build
Featurewise this should be pretty much on par with what appcenter currently does. In my testing it was very reliable and quite fast since it only has to deal with packagekit and not appstream and/or flatpak.
It will send notifications about updates, restart required and update failed.
This goes towards addressing elementary/appcenter#2107. Since we need packagekit for ubuntudrivers anyways I started with this (and because I know packagekit and don't know ubuntu drivers or the distro agnostic driver management mentioned there. The only thing I could find in this direction was an old solus project 🤷)
> Implement system updates

- src/Backends/SystemUpdate.vala
Fixes #90 
Theoretically withdraws old notifications. Not sure if we actually support that in notification center, but at least we can do our part :sweat_smile:
> SystemUpdate: withdraw old notifications on startup

- meson.build
We install nothing to `$datadir/icons/hicolor` right now.
- Same as https://github.com/elementary/files/pull/2294, which unbreaks NixOS build.
> meson: Don't run gtk-update-icon-cache

- po/POTFILES
So that we can translate the provider name in the notification indicator, which is currently shown as untranslated:
> POTFILES: Add autostart.desktop

- data/io.elementary.settings-daemon.gschema.xml
- src/Backends/Housekeeping.vala
Fixes #61
Makes it so we no longer have to rely on GSD for housekeeping options
> HouseKeeping: add temp and trash options

- settings-portal/Settings.vala
Make it resilient to missing GSettings. Also reduce the memory footprint.
> settings-portal: Do not assume GSettings availability

- data/meson.build
#142 is not enough to fix the issue that the provider name in the notification indicator is not translated.
I confirmed it's now shown as translated with this change:
> Localize autostart.desktop

- po/POTFILES
- src/Backends/UbuntuDrivers.vala
Update the driver notification text to be consistent with updates notification (`Updates Available`).
Also update POTFILES while I'm here.
> UbuntuDrivers: Update notification copy

- data/autostart.desktop
Fixes #148
Haven't tested but settings daemon is a GTK app so it will exit if it is launched without an available display, i.e. before the wm.
> wayland: Fix autostart

- src/Backends/SystemUpdate.vala
Also check if something is prepared and if so don't switch to restart required immediately. This can happen if the user logs out and back in again or restarts without installing updates.
elementary/quick-settings#57
> SystemUpdate: Move offline trigger to end session dialog

- meson.build
- src/Application.vala
Based on https://gitlab.archlinux.org/archlinux/packaging/packages/pantheon-settings-daemon/-/commit/e1f48299fdc39d3825fa65cfbcce54678e34a823.
Fixes:
```
../src/Application.vala:140.39-140.65: error: The name `DEVICE_FLAG_UPDATABLE' does not exist in the context of `Fwupd' (fwupd)
140 |                 if (!device.has_flag (Fwupd.DEVICE_FLAG_UPDATABLE)) {
|                                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~'
```
> build: Fix build with fwupd 2.0.0

- src/Backends/SystemUpdate.vala
- src/Backends/UbuntuDrivers.vala
- src/Utils/PkUtils.vala
Fixed https://github.com/elementary/switchboard-plug-about/issues/310
> Add Update Progress Indicator

- src/Backends/SystemUpdate.vala
Fixes elementary/switchboard-plug-about#342
I think this is a racing issue. The plug possibly reads from `last-refresh-time` before Settings Daemon writes to it.
This issue wouldn't happen by making the plug inquire last refresh time from Settings Daemon instead of from GSettings, because Settings Daemon runs in a single thread and the following things happen in order:
- Settings Daemon updates the value of `last_refresh_time` at [SystemUpdate.vala#L103](https://github.com/elementary/settings-daemon/blob/15bbe9602b560c1f00a4ec8d64633d2964c3a815/src/Backends/SystemUpdate.vala#L103)
- When there are no updates, Settings Daemon executes `update_state (UP_TO_DATE);` at [SystemUpdate.vala#L107](https://github.com/elementary/settings-daemon/blob/15bbe9602b560c1f00a4ec8d64633d2964c3a815/src/Backe …
> SystemUpdate: Share last refresh time via DBus

- meson_options.txt
This fixes the following warning on build:
* 1.1.0: {'"boolean option" keyword argument "value" of type str'}
> meson: Fix use of string value for a boolean option

- data/io.elementary.settings-daemon.gschema.xml
- src/Backends/PrefersColorSchemeSettings.vala
Can be rebase merged
Fixes #14 
Fixes #84
Needed to eventually fix #162 
- Adds a new gsetting to set dark mode via settings daemon. This will cut down on duplicate code in Quick Settings and System Settings to set dark mode. Make sure we always handle setting things needed for Mutter, syncing to accountsservice, etc.
- Adds a new bool for snoozed state and set it automatically. This is so you can manually toggle dark mode on and off without canceling your schedule or having the schedule change the setting right back. Snooze will be disabled next time the schedule and color scheme are in sync or the schedule is disabled.
> PrefersColorSchemeSettings: add gsetting 

- data/io.elementary.SettingsDaemon.AccountsService.xml
- src/AccountsService.vala
- src/Backends/InterfaceSettings.vala
Requires and includes https://github.com/elementary/settings-daemon/pull/187
> Sync Wingpanel transparency to Greeter

- data/io.elementary.SettingsDaemon.AccountsService.xml
- settings-portal/Settings.vala
- src/AccountsService.vala
- src/Application.vala
- src/Backends/AccentColorManager.vala
Fixes https://github.com/elementary/settings-daemon/issues/149
Changes:
- Set Gtk theme here instead of in settings plug
- Cache calculated dynamic accent color in out settings account service and use it in portal, which fixes https://github.com/elementary/settings-daemon/issues/149. And it can be used to fix https://github.com/elementary/greeter/issues/689
> Cache dynamic accent color in account settings and use it in Portal

- src/Backends/Housekeeping.vala
Fixes a bug introduced in https://github.com/elementary/settings-daemon/pull/143
If you enable housekeeping for temp and trashed files only, it won't work because is_disabled was never updated to account for these options.
> Fix housekeeping

- data/io.elementary.SettingsDaemon.AccountsService.xml
- src/AccountsService.vala
- src/Backends/InterfaceSettings.vala
Required for https://github.com/elementary/greeter/pull/814
> Sync wingpanel's "Show Percentage" option
